# Generated by Django 4.2.4 on 2023-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.BigIntegerField(default='123456789'),
        ),
    ]
