# Generated by Django 4.2.4 on 2023-09-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0002_userprofile_email_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
