# Generated by Django 4.2.4 on 2023-09-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('laptop-repair', 'Laptop Repair'), ('mobile-repair', 'Mobile Device Repair'), ('tablet-repair', 'Tablet Repair'), ('desktop-repair', 'Desktop Repair'), ('software-install', 'Software Installation'), ('upgrades-maintenance', 'Upgrades & Maintenance')], max_length=255),
        ),
    ]
