# Generated by Django 4.2.4 on 2023-09-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0006_alter_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('laptop-repair', 'Laptop Repair'), ('mobile-repair', 'Mobile Device Repair'), ('tablet-repair', 'Tablet Repair'), ('desktop-repair', 'Desktop Repair'), ('software-install', 'Software Installation'), ('upgrades-maintenance', 'Upgrades & Maintenance')], max_length=20),
        ),
    ]
