# Generated by Django 4.2.4 on 2023-10-04 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0007_remove_booking_created_at_alter_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('laptop-repair', 'Laptop Repair'), ('mobile-repair', 'Mobile Device Repair'), ('tablet-repair', 'Tablet Repair'), ('desktop-repair', 'Desktop Repair'), ('software-install', 'Software Installation'), ('upgrades-maintenance', 'Upgrades & Maintenance')], max_length=100),
        ),
    ]
